"""add scope to permission

Revision ID: 11b469c6d972
Revises: 1bdbff5ce391
Create Date: 2026-06-02 18:14:45.204769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b469c6d972'
down_revision = '1bdbff5ce391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nav_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_nav_item_section_slug'), type_='unique')

    with op.batch_alter_table('nav_section', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_nav_section_name'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nav_section', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_nav_section_name'), ['name'])

    with op.batch_alter_table('nav_item', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_nav_item_section_slug'), ['section_id', 'page_slug'])

    # ### end Alembic commands ###
