"""add_is_favorite_to_agent_conversation

Revision ID: 75c0ec3212cc
Revises: f5g6h7i8j9k0
Create Date: 2026-05-08 19:40:19.187725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c0ec3212cc'
down_revision = 'f5g6h7i8j9k0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_conversation', schema=None) as batch_op:
        batch_op.drop_column('is_favorite')

    # ### end Alembic commands ###
